image: node:18.20.5
definitions:
  caches:
    nextcache: .next/cache
pipelines:
  custom:
    push_to_preprod:
    - step:
        caches:
        - node
        - nextcache
        oidc: true
        name: 'Push to preprod'
        script:
          - export AWS_REGION=ap-south-1
          - export AWS_ROLE_ARN=arn:aws:iam::324298177213:role/bitbucket-pipelines
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - npm install -f
          - npm run build
          - apt-get update -y && apt-get install awscli -y
          - aws s3 sync .next s3://cc-lms-pp/.next
    push_to_prod:
    - step:
        caches:
        - node
        - nextcache
        oidc: true
        name: 'Push to prod'
        script:
          - export AWS_REGION=ap-south-1
          - export AWS_ROLE_ARN=arn:aws:iam::324298177213:role/bitbucket-pipelines
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - npm install -f
          - npm run build
          - apt-get update -y && apt-get install awscli -y
          - aws s3 sync .next s3://cc-lms-production/.next